---
- name: set timezone
  command: timedatectl set-timezone America/New_York

- name: check if swap is already on
  command: swapon -s
  register: result

# - debug: var=result

- name: do the swap file if swap has not been set
  include: swapon.yml
  when: result.stdout == ""

- name: first run if its a new machine (variable in defaults/main.yml)
  include: firstrun.yml
  when: do_FirstRun

- name: upgrade when pushing out docker updates (variable in defaults/main.yml)
  include: upgrade.yml
  when: do_Upgrade