---
version: '2'
services:
  traefik:
    image: traefik:alpine
    #command: --web --docker --docker.domain=docker.localhost --docker.watch --logLevel=ERROR --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443' --defaultEntryPoints='http' --accessLogsFile='log/access.log'
    #command: --web --docker --docker.domain=docker.localhost --docker.watch --logLevel=ERROR --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS:CipherSuites:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS:tls/651f1c6989eb5f4.crt,tls/tekstream.com.key' --defaultEntryPoints='http,https' --accessLogsFile='log/access.log'
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /opt/appdata/traefik/certs/:/tls
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  #whoami:
    #image: emilevauge/whoami labels:
      #- "traefik.backend=whoami" - "traefik.frontend.rule=Path:/whoami"
  jira:
    #ports:
      #- "8080:8080"
    image: cptactionhank/atlassian-jira:latest
    container_name: jira
    volumes:
      - /opt/appdata/jira/home:/var/atlassian/jira
      - /opt/appdata/jira/logs:/opt/atlassian/jira/logs
      #- /opt/appdata/jira/jirawebaction:/opt/atlassian/jira/atlassian-jira/WEB-INF/classes/com/atlassian/jira/web/action:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.backend=jira"
      - "traefik.frontend.rule=Host:jiradev.tekstream.com"
      #- "traefik.enable=false"
    environment:
      #- "CATALINA_OPTS= -Xms2G -Xmx2G"
      - X_PROXY_NAME=jiradev.tekstream.com
      - X_PROXY_PORT=443
      - X_PROXY_SECURE=true
      - X_PROXY_SCHEME=https
    restart: always
    depends_on:
      - postgres
  # servicedesk:
  #   #ports:
  #     #- "8080:8080"
  #   image: cptactionhank/atlassian-jira-service-desk:3.9.1
  #   container_name: servicedesk
  #   volumes:
  #     - /opt/appdata/servicedesk/home:/var/atlassian/jira
  #     - /opt/appdata/servicedesk/logs:/opt/atlassian/jira/logs
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   labels:
  #     - "traefik.backend=servicedesk"
  #     - "traefik.frontend.rule=Host:servicedeskdev.tekstream.com"
  #     #- "traefik.enable=false"
  #   environment:
  #     - "CATALINA_OPTS= -Xms2G -Xmx2G"
  #     - X_PROXY_NAME=servicedeskdev.tekstream.com
  #     - X_PROXY_PORT=443
  #     - X_PROXY_SECURE=true
  #     - X_PROXY_SCHEME=https
  #   restart: always
  #   depends_on:
  #     - postgres
  confluence:
    #ports:
    #  - "8090:8090"
    image: cptactionhank/atlassian-confluence:7.3.2
    container_name: confluence
    volumes:
      - /opt/appdata/confluence/home:/var/atlassian/confluence
      - /opt/appdata/confluence/logs:/opt/atlassian/confluence/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.backend=confluence"
      - "traefik.frontend.rule=Host:confluencedev.tekstream.com"
    environment:
      #- "CATALINA_OPTS= -Xms2G -Xmx2G"
      - X_PROXY_NAME=confluencedev.tekstream.com
      - X_PROXY_PORT=443
      - X_PROXY_SECURE=true
      - X_PROXY_SCHEME=https
    restart: always
    depends_on:
      - postgres
  # confluence:
  #   #ports:
  #   #  - "8090:8090"
  #   image: atlassian/confluence-server:6.7.0
  #   container_name: confluence
  #   volumes:
  #     - /opt/appdata/confluence_new/home:/var/atlassian-data/confluence
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   labels:
  #     - "traefik.backend=confluence"
  #     - "traefik.frontend.rule=Host:confluencedev.tekstream.com"
  #   environment:
  #     - JVM_MINIMUM_MEMORY=2G
  #     - JVM_MAXIMUM_MEMORY=2G
  #     - CATALINA_CONNECTOR_PROXYNAME=confluencedev.tekstream.com
  #     - CATALINA_CONNECTOR_PROXYPORT=80
  #     - CATALINA_CONNECTOR_SECURE=false
  #     - CATALINA_CONNECTOR_SCHEME=http
  #   restart: always
  #   depends_on:
  #     - postgres
  bitbucket:
    #ports:
    #  - "7990:7990" - "7999:7999"
    image: atlassian/bitbucket-server:6.9.0
    container_name: bitbucket
    volumes:
      - /opt/appdata/bitbucket/home:/var/atlassian/application-data/bitbucket
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.backend=bitbucket"
      - "traefik.frontend.rule=Host:bitbucketdev.tekstream.com"
    environment:
      - SERVER_SECURE=true
      - SERVER_SCHEME=https
      - SERVER_PROXY_PORT=443
      - SERVER_PROXY_NAME=bitbucketdev.tekstream.com
    restart: always
    depends_on:
      - postgres
  postgres:
    #ports:
    #  - "5432:5432"
    image: postgres:9.5
    container_name: postgres
    volumes:
      - /opt/appdata/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=false"
    restart: always
  pgadmin:
    ports:
      - "5050:80"
      - "5051:443"
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - /opt/appdata/pgadmin:/var/lib/pgadmin
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    labels:
      - "traefik.backend=pgadmin"
      - "traefik.frontend.rule=Host:pgadmin.tekstream.com"
      - "traefik.enable=false"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=tekstream@tekstream.com"
      - "PGADMIN_DEFAULT_PASSWORD=t3kStReam"
    depends_on:
      - postgres
  portainer:
    ports:
      - "9000:9000"
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer/:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainerdev.tekstream.com"
      - "traefik.enable=false"
  snipe-mysql:
    image: mysql:5
    container_name: snipe-mysql
    restart: always
    volumes:
      - /opt/appdata/snipeit/mysql/:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_ROOT_PASSWORD=t3k$$tReam
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=t3k$$tReam
      - MYSQL_DATABASE=snipe
    labels:
      - "traefik.backend=mysql"
      - "traefik.frontend.rule=Host:mysqldev.tekstream.com"
      - "traefik.enable=false"
  snipe-it:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - snipe-mysql
    volumes:
      - /opt/appdata/snipeit/snipeit_config/:/config
    environment:
      - APP_URL=https://snipeitdev.tekstream.com
      - MYSQL_PORT_3306_TCP_ADDR=snipe-mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=t3k$$tream
      - PGID=1001
      - PUID=1001
    labels:
      - "traefik.backend=snipeit"
      - "traefik.frontend.rule=Host:snipeitdev.tekstream.com"
      - "traefik.enable=true"
  # mariadb:
  #   ports:
  #     - "3306:3306"
  #   image: mariadb:10.3
  #   container_name: mariadb
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=changeme
  #     - MYSQL_DATABASE=RDM
  #     - MYSQL_RANDOM_ROOT_PASSWORD=yes
  #   volumes:
  #     - /opt/appdata/mariadb/:/var/lib/mysql
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   restart: always
  #   labels:
  #     - "traefik.backend=mariadb"
  #     - "traefik.frontend.rule=Host:mariadev.tekstream.com"
  #     - "traefik.enable=false"
  # mysql:
  #   ports:
  #     - "3307:3306"
  #   image: mysql:8
  #   container_name: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=changeme
  #     - MYSQL_DATABASE=RDM
  #     - MYSQL_RANDOM_ROOT_PASSWORD=yes
  #   volumes:
  #     - /opt/appdata/mysql/:/var/lib/mysql
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   restart: always
  #   labels:
  #     - "traefik.backend=marimysqladb"
  #     - "traefik.frontend.rule=Host:mysqldev.tekstream.com"
  #     - "traefik.enable=false"
  # mssql:
  #   ports:
  #     - "1433:1433"
  #   image: microsoft/mssql-server-linux:latest
  #   container_name: mssql
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=changeme
  #     - MSSQL_PID=Express
  #   volumes:
  #     - /opt/appdata/mssql/:/var/opt/mssql
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   restart: always
  #   labels:
  #     - "traefik.backend=mssql"
  #     - "traefik.frontend.rule=Host:mssqldev.tekstream.com"
  #     - "traefik.enable=false"
  # tasktop:
  #   ports:
  #     - "8082:8080"
  #     - "8334:8443"
  #   image: postupunsub/tasktop-integration-hub
  #   container_name: tasktop
  #   # environment:
  #   volumes:
  #     # - /opt/appdata/tasktop/:/var/opt/mssql
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #   restart: always
  #   labels:
  #     - "traefik.backend=tasktop"
  #     - "traefik.frontend.rule=Host:tasktop.tekstream.com"
  #     - "traefik.enable=false"